"""create_user_table

Revision ID: 01280e85dfa8
Revises: 
Create Date: 2022-07-26 16:34:37.676952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01280e85dfa8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
