"""create-relation-user-pages

Revision ID: 2115315da2db
Revises: d3f4e1ff8e66
Create Date: 2022-07-29 17:48:02.799462

"""
from venv import create
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2115315da2db'
down_revision = 'd3f4e1ff8e66'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pages')
    op.drop_table('users')
    op.create_table('users',
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key')
    )
    op.create_table('pages',
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('owner_id',sa.Integer(),nullable=False),
    sa.PrimaryKeyConstraint('id', name='pages_pkey')
    
    )
    op.create_foreign_key("page_user_fk",source_table="pages",referent_table="users",local_cols=['owner_id'],
                          remote_cols=['id'],ondelete='CASCADE')
   
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("page_user_fk",table_name='pages')
    op.drop_table('pages')
    op.drop_table('users')
    # ### end Alembic commands ###
