"""create_user_table

Revision ID: 57e0af6b9539
Revises: 01280e85dfa8
Create Date: 2022-07-26 16:38:25.821995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57e0af6b9539'
down_revision = '01280e85dfa8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
