"""create_user_table

Revision ID: a1c29e7795a3
Revises: d2509cdba52d
Create Date: 2022-07-26 16:51:33.472969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1c29e7795a3'
down_revision = 'd2509cdba52d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
